apiVersion: v1
kind: Service
metadata:
  name: chat-app
spec:
  type: LoadBalancer
  selector:
    app: chat-app
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-app
spec:
  selector:
    matchLabels:
      app: chat-app
  template:
    metadata:
      labels:
        app: chat-app
    spec:
      containers:
      - name: chat-app
        image: skaffold-chat-app
        ports:
        - containerPort: 3000
