apiVersion: skaffold/v2beta21
kind: Config
build:
  artifacts:
  - image: react-app
    context: app
    sync:
      manual:
      - src: 'src/components/*'
        dest: .
      - src: 'src/styles/*'
        dest: .
