apiVersion: v1
kind: Service
metadata:
  name: chatroom-frontend
spec:
  type: LoadBalancer
  selector:
    app: chatroom-frontend
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatroom-frontend
spec:
  selector:
    matchLabels:
      app: chatroom-frontend
  template:
    metadata:
      labels:
        app: chatroom-frontend
    spec:
      containers:
      - name: chatroom-frontend
        image: skaffold-chatroom-frontend
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"
        ports:
        - containerPort: 3000