apiVersion: v1
kind: Service
metadata:
  name: chatroom-backend
spec:
  type: LoadBalancer
  selector:
    app: chatroom-backend
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatroom-backend
spec:
  selector:
    matchLabels:
      app: chatroom-backend
  template:
    metadata:
      labels:
        app: chatroom-backend
    spec:
      containers:
      - name: chatroom-backend
        image: skaffold-chatroom-backend
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"
        ports:
        - containerPort: 8000