apiVersion: v1
kind: Service
metadata:
  name: chatroom-frontend
spec:
  type: LoadBalancer
  selector:
    app: chatroom-frontend
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatroom-frontend
spec:
  selector:
    matchLabels:
      app: chatroom-frontend
  template:
    metadata:
      labels:
        app: chatroom-frontend
    spec:
      containers:
      - name: chatroom-frontend
        image: skaffold-chatroom-frontend
        ports:
        - containerPort: 3000