apiVersion: skaffold/v2beta21
kind: Config
metadata:
  name: chat-app
build:
  artifacts:
  - image: skaffold-create-react-app
    sync:
      infer:
      - '**/*.js'
      - '**/*.ts'
      - '**/*.tsx'
      - '**/*.css'
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - k8s/deployment.yaml